spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/workoutwith?useSSL=false&&serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: workoutwithproject@gmail.com
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
        starttls:
          enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template: true
    cache: false
  redis:
    host: http://3.36.81.47/
    port: 6379

email:
  from:
    address: workoutwithproject@gmail.com

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

cloud:
  aws:
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: workoutwith-bucket/images
    region:
      auto: false
      static: ap-northeast-2
  task:
    execution:
      pool:
        core-size: 5
        max-size: 5
